name: Update README

on:
  schedule:
    - cron: "0 * * * *"  # 每小時執行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: lcwihaoei/github-activity-readme@master
        env:
          GH_TOKEN: ${{ secrets.README_TOKEN }}
