name: Update README
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update README activity
        uses: lcwihaoei/github-activity-readme@master
        env:
          # 用你剛建立的 Classic PAT（Secret 名稱要完全相同）
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
          # 若你改用內建 token，則：
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
