name: Update README on any push

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Debug env
        run: |
          set -x
          git --version
          ls -la
          echo "BRANCH=${GITHUB_REF_NAME}"

      - name: Ensure README exists and markers present
        run: |
          if [ ! -f README.md ]; then
            echo "# Smart Parking System" > README.md
          fi
          if ! grep -q "<!--START_SECTION:status-->" README.md; then
            cat >> README.md <<'EOF'

<!--START_SECTION:status-->
Placeholder
<!--END_SECTION:status-->
EOF
          fi

      - name: Generate snippet
        id: gen
        run: echo "SNIPPET=Last update: $(date -u) | branch: ${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Replace between markers (robust)
        run: |
          SNIPPET="${{ steps.gen.outputs.SNIPPET }}"
          # 用 perl 處理整檔（-0777 讀整個檔；s 修飾符 /s 讓 . 匹配換行）
          perl -0777 -pe 'BEGIN{$s=q('"'"$SNIPPET"'"')}
            s/<!--START_SECTION:status-->.*?<!--END_SECTION:status-->/<!--START_SECTION:status-->\n$s\n<!--END_SECTION:status-->/s
          ' README.md > README.new || { echo "::error::replace failed"; exit 2; }
          mv README.new README.md
          echo "----- README preview -----"
          sed -n '1,80p' README.md

      - name: Commit if changed
        run: |
          if git diff --quiet; then
            echo "No changes"; exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: auto-update README [skip ci]"
          git push
