name: Update GitHub Activity

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure README.md exists
        run: |
          if [ ! -f README.md ]; then
            echo "# Smart Parking System" > README.md
            echo "" >> README.md
            echo "<!--START_SECTION:status-->" >> README.md
            echo "Last update: $(date) | branch: '${{ github.ref_name }}'" >> README.md
            echo "<!--END_SECTION:status-->" >> README.md
          fi

      - name: Detect file changes
        run: |
          CHANGES=$(git status --porcelain)
          if [ -z "$CHANGES" ]; then
            echo "No changes detected" >> README.md
          else
            echo "File changes detected:" >> README.md
            echo "$CHANGES" >> README.md
          fi

      - name: Force add README.md
        run: |
          git add README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Update README with latest activity" || echo "No changes to commit"
          git push
