name: Update README on any push

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Ensure README and markers
        run: |
          if [ ! -f README.md ]; then
            echo "# Smart Parking System" > README.md
          fi
          if ! grep -q "<!--START_SECTION:status-->" README.md; then
            cat >> README.md <<'EOF'

<!--START_SECTION:status-->
Placeholder
<!--END_SECTION:status-->
EOF
          fi

      - name: Generate snippet
        id: gen
        run: echo "SNIPPET=Last update: $(date -u) | branch: ${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Replace between markers (Python, safe)
        run: |
          python3 - <<'PY'
          import io,sys,re,os
          fname="README.md"
          with io.open(fname,"r",encoding="utf-8") as f:
              txt=f.read()
          snippet=os.environ.get("SNIPPET","")
          pat=re.compile(r"<!--START_SECTION:status-->.*?<!--END_SECTION:status-->", re.S)
          repl=f"<!--START_SECTION:status-->\n{snippet}\n<!--END_SECTION:status-->"
          new=pat.sub(repl, txt)
          with io.open(fname,"w",encoding="utf-8",newline="\n") as f:
              f.write(new)
          PY
        env:
          SNIPPET: ${{ steps.gen.outputs.SNIPPET }}

      - name: Commit if changed
        run: |
          if git diff --quiet; then
            echo "No changes"; exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: auto-update README [skip ci]"
          git push
