name: Update GitHub Activity

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure README.md exists
        run: |
          if [ ! -f README.md ]; then
            echo "# Smart Parking System" > README.md
            echo "" >> README.md
            echo "<!--START_SECTION:status-->" >> README.md
            echo "Last update: $(date) | branch: '${{ github.ref_name }}'" >> README.md
            echo "<!--END_SECTION:status-->" >> README.md
          fi

      - name: Detect file changes
        run: |
          CHANGES=$(git status --porcelain)
          if [ -z "$CHANGES" ]; then
            echo "No changes detected" >> README.md
          else
            echo "File changes detected:" >> README.md
            echo "$CHANGES" >> README.md
          fi

      - name: Generate SNIPPET
        id: gen_snippet
        run: |
          echo "SNIPPET=Last update: $(date) | branch: '${{ github.ref_name }}'" >> $GITHUB_ENV

      - name: Replace between markers (Python, safe)
        run: |
            python3 - <<PY
            import io, os, re
            fname = "README.md"
            with io.open(fname, "r", encoding="utf-8") as f:
                txt = f.read()
            snippet = os.environ.get("SNIPPET", "Last update: Placeholder")
            pat = re.compile(r"<!--START_SECTION:status-->.*?<!--END_SECTION:status-->", re.S)
            if pat.search(txt):
                new = pat.sub(f"<!--START_SECTION:status-->\\n{snippet}\\n<!--END_SECTION:status-->", txt)
            else:
                new = txt + f"\\n<!--START_SECTION:status-->\\n{snippet}\\n<!--END_SECTION:status-->"
            with io.open(fname, "w", encoding="utf-8", newline="\\n") as f:
                f.write(new)
            PY
        env:
          SNIPPET: ${{ env.SNIPPET }}

      - name: Commit and push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: auto-update README [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"